baseURL = "http://sf23.locus.com.np/"
languageCode = "en-us"
title = "Software Fellowship 2023"
theme = "minimal"
googleAnalytics = ""



[params]
    author = "Aayush Neupane"
    description = "Locus Software Fellowship Home"
    githubUsername = "Atomnp"
    accent = "purple"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/days/"
    name = "Content"
    weight = 3


# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:neupane0403@gmail.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/Atomnp/"
    name = "fab fa-github"
    weight = 2

